### ISSUE TITLE
From your Team Member for the Hacksquad event!

### ISSUE THREAD

**Issue by ShikhaKumari01** [SOUMEN-PAL/Android_Projects_Learning#1]
Hello Soumen! Shikha this side.

Sorry for texting here, but I don't have any other way to reach you.

This is an email regarding the Hacksquad contribution. 

I want to tell you that I am the team member of our team Extensive. So, for the sake of winning this open source contribution, we have to contribute more and more.

I just want to tell you that we have to be active. 

I hope that you'll show your active participation.

For more information, you can connect with me on the other social media handle.

Contact me

LinkedIn: https://www.linkedin.com/in/shikha-kumari-0b58a6257?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

**Comment by SOUMEN-PAL** [comment]
Sorry for my absence I hope i didn't cause problem i suffered from Dengue and was unavailable at that time.
